### ISSUE TITLE
wish add the Quest control

### ISSUE THREAD

**Issue by ole100** [Macx-Lio/MultiBot#10]
Hi Macx,
 Wish you can add quest control bot's quests.
 Some time my quest failed so need giveup my and my bot's quest and do it again.  
![image](https://github.com/user-attachments/assets/ea73b44e-022b-4832-8367-f48c4c9ddded)

**Comment by Macx-Lio** [comment]
Hello Ole100,

I read your wish.
I will look what I can do.

Have Fun :D

**Comment by Macx-Lio** [comment]
Hello Ole100,

I added the new Feature "Quest-Control".

![image](https://github.com/user-attachments/assets/b0c72de1-611f-4e54-886e-8a84ee9815c4)

Now you can easy share or abandon Quest with your Bots.

Have Fun :D

**Comment by Macx-Lio** [comment]
P.S. The Bots must be in your Party or Raid, else you cant share or abandon the Quest with them.

**Comment by ole100** [comment]
Hello Macx,
 Thanks for you nice work.
 I Think it's batter add new Feature for every bot to control every bot's quest.
![image](https://github.com/user-attachments/assets/d61d9b6b-a926-49d8-90b7-5302f5bcd8a2)

**Comment by Macx-Lio** [comment]
Hello Ole100,

unfortunately, I have to inform you that the 3.3.5 LUA only can access the current Character's Quest-List.
Therefore, it is not possible for me, to get Quest-List of the individual Bot (because they are akting as differend Players).
I only can ask, if a Bot has the same Quest like your current Character.
This means I cannot make any indiviual Quest-Control for any Bots.

Have Fun :D
