### ISSUE TITLE
Missing Function

### ISSUE THREAD

**Issue by R0thgas** [Macx-Lio/MultiBot#6]
First thx super nice addon.

I miss a function from Unbot -> "set (all) bot online".

I found out, that I can readd chars and mostly there will be the same, but often the Tool creates a new lvl 1 char.

Maybe this is a Problem cause my server is to slow, then i would wish to set a cooldown.

**Comment by Macx-Lio** [comment]
The Tool does not create the Bots.
The Tool only tells Mod-Playerbot to do it.
If you get Level 1 Characters you should add this Issue on the Mod-Playerbot Buglist.
I will take a look where I could find a Space for such a Button.

**Comment by Macx-Lio** [comment]
Hello R0thgas,

I have added Equivalent to the ".playerbot bot add *"-Command.

As long you are not in a Raid or Group, a Right-Click on the Invite-Control will add all Bots of the current Roster.
If you are in a Group, a Right-Click will remove all Bots from your Raid or Party.

![image](https://github.com/user-attachments/assets/d832215d-1988-406c-92f5-62821196ba60)

I dont use the ".playerbot bot all *"-Command, because it doesnt work in my current Version of Mod-Playerbot.
To ensure you get all Bots online, I use the MultiBot internal System to add the Bots.
This also has the Benefit, that you could invite the Bots of the Guild- or Friendlist.

The OR is important., because the Right-Click to invite does only work as long you are not in a Group.
So you could invite all Altbots OR Guildbots OR Friendbots at once.

Hope this Function is what your are looking for.

Have Fun :D

**Comment by R0thgas** [comment]
Thank you, I'll test it and give u feedback.
